AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE

AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY

github_token=ghp_1234567890abcdefghijklmnopqrstuvwxyz1234

DB_USERNAME=admin

DB_PASSWORD=Admin@123456
